# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/testfile.coe}}
read_vhdl -library xil_defaultlib {
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/PWM.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/SevenSeg_MUX.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/alu.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/clk_divider.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/cpu.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/microram_sim.vhd}
  {C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/sources_1/new/Microprocessor_Top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/constrs_1/new/cpu_pins.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jason/Desktop/EGR 426/Project3/EGR-426-Project-3/cpu.srcs/constrs_1/new/cpu_pins.xdc}}]


synth_design -top Microprocessor_Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Microprocessor_Top.dcp

catch { report_utilization -file Microprocessor_Top_utilization_synth.rpt -pb Microprocessor_Top_utilization_synth.pb }
